/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Game: typeof import('./src/components/Game.vue')['default']
    Gues: typeof import('./src/components/GuessHistory/Gues.vue')['default']
    GuessHistory: typeof import('./src/components/GuessHistory/GuessHistory.vue')['default']
    GuessItem: typeof import('./src/components/GuessHistory/GuessItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    StatsBar: typeof import('./src/components/StatsBar.vue')['default']
  }
}
