/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ClosestWords: typeof import('./src/components/ClosestWords.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GuessHistory: typeof import('./src/components/GuessHistory/GuessHistory.vue')['default']
    GuessItem: typeof import('./src/components/GuessHistory/GuessItem.vue')['default']
    HowToPlay: typeof import('./src/components/HowToPlay.vue')['default']
    PreviousGames: typeof import('./src/components/PreviousGames.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    StatsBar: typeof import('./src/components/StatsBar.vue')['default']
    StatsCard: typeof import('./src/components/StatsCard.vue')['default']
  }
}
